const SEAT_STATUS = [
  [
    {available: true, selected: false},
    {available: true, selected: false},
    {available: false, selected: false},
    {available: false, selected: false},
  ],
  [
    {available: true, selected: false},
    {available: true, selected: false},
    {available: true, selected: false},
    {available: true, selected: false},
    {available: false, selected: false},
    {available: false, selected: false},
    {available: false, selected: false},
    {available: true, selected: false},
    {available: true, selected: false},
  ],
  [
    {available: true, selected: false},
    {available: false, selected: false},
    {available: false, selected: false},
    {available: false, selected: false},
    {available: false, selected: false},
    {available: true, selected: false},
    {available: true, selected: false},
    {available: true, selected: false},
    {available: true, selected: false},
  ],
  [
    {available: false, selected: false},
    {available: true, selected: false},
    {available: true, selected: false},
    {available: true, selected: false},
    {available: true, selected: false},
    {available: true, selected: false},
    {available: false, selected: false},
    {available: true, selected: false},
    {available: true, selected: false},
  ],
  [
    {available: false, selected: false},
    {available: true, selected: false},
    {available: false, selected: false},
    {available: false, selected: false},
    {available: true, selected: false},
    {available: true, selected: false},
    {available: true, selected: false},
    {available: true, selected: false},
    {available: false, selected: false},
  ],
  [
    {available: true, selected: false},
    {available: true, selected: false},
    {available: true, selected: false},
    {available: true, selected: false},
    {available: true, selected: false},
    {available: false, selected: false},
    {available: true, selected: false},
  ],
];

export default SEAT_STATUS;
